#define IDB_TOOLS_GROUP       100
#define IDB_PENCIL_TOOL       101
#define IDB_LINE_TOOL         102
#define IDB_BEZIER_TOOL       103
#define IDB_RECTANGLE_TOOL    104
#define IDB_ELLIPSE_TOOL      105
#define IDB_ERASER_TOOL       106
#define IDB_COLOR_GROUP       107
#define IDB_FILL_CHECK        108
#define IDB_WIDTH_GROUP       109
#define IDB_BORDER_WIDTH      110
#define IDB_CLEAR_BUTTON      111
#define HK_DRAW_ELLIPSE       112
#define HK_BLUE_COLOR         113
